name: Auto Update Fuel Price
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-price:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # 將 v3 改為 v4
      - uses: actions/checkout@v4
      
      # 將 v3 改為 v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - run: node scraper.js
      
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add prices.json
          git commit -m "Auto-update fuel price" || exit 0
          git push
